### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by tomdrops** [SergeyMosin/Appointments#27]
HI.

Unfortunately there is no link to the privacy policy and a check box to accept prior to booking an appointment. Unless this criteria is met the app cannot be used within the EU due to GDPR requirements.

**Comment by SergeyMosin** [comment]
What does the check box text usually say? Can you provide a screen shot of GDPR complaint form.
Thank you.

**Comment by mokkin** [comment]
Maybe a link to the built in nextcloud feature for that would be sufficient?

![image](https://user-images.githubusercontent.com/2938748/76439132-399fd900-63bc-11ea-8851-26f2ba34eb81.png)

**Comment by tomdrops** [comment]
> Maybe a link to the built in nextcloud feature for that would be sufficient?
> 
> ![image](https://user-images.githubusercontent.com/2938748/76439132-399fd900-63bc-11ea-8851-26f2ba34eb81.png)

Somehow yes, but only with a checkbox "I have read and accepted the privacy policy." and maybe two lines of explanation. GDPR requires to inform the user prior to sending data how it will be processed....

**Comment by nolens** [comment]
@SergeyMosin 
Nice solution in latest version!
However, one little issue: 

- If user does not tick the "checkbox", there is an error showing "phone number required". 
- Expected behavior: Error message "Please tick this box" should show.

**Comment by SergeyMosin** [comment]
The "Phone Number Required" message is your browser's built-in way of form validation and refers to the empty phone number field (see screenshots below).
The checkbox does not have it's own "error message" as of now because of the NC styling, it just turns the border red when not checked.
If you want you can "hack" the CSS and add some spacing to the checkbox by adding the following to the **GDPR Compliance** field in the settings:
```css
your_text_here... <style>.srgdev-ncfp-chb-cont{margin-top:2.5em;}</style>
```
or make it fancy with a border :)
```css
your_text_here... <style>.srgdev-ncfp-chb-cont{margin-top:1.5em; border-top: 1px solid var(--color-border-dark); padding-top:1em;}</style>
```
----

browser's built-in phone# validation screenshots...
![gdpr](https://user-images.githubusercontent.com/10747559/77078700-53997700-69cd-11ea-89de-b4da094f51cb.jpg)
